import path from "node:path";
import { cpmRoot } from "./paths.js";
import { atomicWrite } from "./fs.js";
import { providers } from "../providers/catalog.js";
import { providerScope, resolveSecret } from "./vault.js";

export type ShellKind = "dotenv" | "bash" | "zsh" | "fish" | "powershell";

function quoteSingle(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** PowerShell single-quoted strings escape a quote by doubling it. */
function quotePowerShell(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function renderLine(shell: ShellKind, key: string, value: string): string {
  switch (shell) {
    case "dotenv":
      return `${key}=${JSON.stringify(value)}`;
    case "fish":
      return `set -gx ${key} ${quoteSingle(value)};`;
    case "powershell":
      return `$env:${key} = ${quotePowerShell(value)}`;
    case "bash":
    case "zsh":
      return `export ${key}=${quoteSingle(value)}`;
    default: {
      const _exhaustive: never = shell;
      throw new Error(`Unknown shell: ${_exhaustive}`);
    }
  }
}

export function envFilePath(home: string, shell: ShellKind): string {
  const extension = shell === "powershell" ? "ps1" : shell === "fish" ? "fish" : shell === "dotenv" ? "env" : "sh";
  return path.join(cpmRoot(home), "env", `active.${extension}`);
}

export async function materializeActiveEnvironment(home: string, shell: ShellKind = "dotenv"): Promise<string> {
  // Permissions: atomicWrite applies POSIX 0600 / Windows ACL lockdown (best-effort).
  const lines = ["# Generated by CPM. Contains active provider secrets. Owner-only permissions (0600 / Windows ACL)."];
  for (const provider of providers) {
    try {
      const resolved = await resolveSecret(home, providerScope(provider.id), undefined, provider.keyEnv);
      lines.push(renderLine(shell, provider.keyEnv, resolved.value));
    } catch {
      // Provider is intentionally omitted when it has no active key.
    }
  }
  const file = envFilePath(home, shell);
  await atomicWrite(file, `${lines.join("\n")}\n`);
  return file;
}
