import type { AuthFlow } from "../types.js";

export const authFlows: AuthFlow[] = [
  {
    id: "codex-chatgpt",
    displayName: "Codex: sign in with ChatGPT",
    kind: "oauth-browser",
    tool: "codex",
    provider: "openai",
    command: "codex",
    args: ["login"],
    statusArgs: ["login", "status"],
    logoutArgs: ["logout"],
    headless: false,
    notes: ["Credentials remain owned by Codex in its configured credential store."],
  },
  {
    id: "codex-openai-key",
    displayName: "Codex: import OpenAI API key",
    kind: "api-key-login",
    tool: "codex",
    provider: "openai",
    providerKey: "openai",
    command: "codex",
    args: ["login", "--with-api-key"],
    statusArgs: ["login", "status"],
    logoutArgs: ["logout"],
    headless: true,
    notes: ["CPM pipes the selected key through stdin; it is never placed in process arguments."],
  },
  {
    id: "codex-access-token",
    displayName: "Codex: import managed OAuth access token",
    kind: "api-key-login",
    tool: "codex",
    provider: "openai",
    secretScope: "auth/codex-access-token",
    secretEnv: "CODEX_ACCESS_TOKEN",
    command: "codex",
    args: ["login", "--with-access-token"],
    statusArgs: ["login", "status"],
    logoutArgs: ["logout"],
    headless: true,
    notes: ["For managed/headless workflows. Store with: cpm secret add auth/codex-access-token <alias>."],
  },
  {
    id: "opencode-openai-chatgpt",
    displayName: "OpenCode: OpenAI/ChatGPT login",
    kind: "oauth-browser",
    tool: "opencode",
    provider: "openai",
    command: "opencode",
    args: ["auth", "login", "--provider", "openai"],
    statusArgs: ["auth", "list"],
    logoutArgs: ["auth", "logout"],
    headless: false,
    notes: ["OpenCode presents its currently available OpenAI authentication methods."],
  },
  {
    id: "opencode-github-copilot",
    displayName: "OpenCode: GitHub Copilot device login",
    kind: "oauth-device",
    tool: "opencode",
    provider: "github-copilot",
    command: "opencode",
    args: ["auth", "login", "--provider", "github-copilot"],
    statusArgs: ["auth", "list"],
    logoutArgs: ["auth", "logout"],
    headless: true,
  },
  {
    id: "opencode-gitlab-duo",
    displayName: "OpenCode: GitLab Duo login",
    kind: "oauth-device",
    tool: "opencode",
    provider: "gitlab-duo",
    command: "opencode",
    args: ["auth", "login", "--provider", "gitlab-duo"],
    statusArgs: ["auth", "list"],
    logoutArgs: ["auth", "logout"],
    headless: true,
  },
  {
    id: "gemini-google",
    displayName: "Gemini CLI: Sign in with Google",
    kind: "oauth-browser",
    tool: "gemini-cli",
    provider: "google",
    command: "gemini",
    args: [],
    headless: false,
    notes: ["Select 'Sign in with Google' in Gemini CLI. Gemini owns and refreshes the cached credentials."],
  },
  {
    id: "gemini-vertex-adc",
    displayName: "Gemini CLI: Vertex AI application-default credentials",
    kind: "oauth-browser",
    tool: "gemini-cli",
    provider: "google-vertex",
    command: "gcloud",
    args: ["auth", "application-default", "login"],
    headless: false,
    notes: ["GOOGLE_CLOUD_PROJECT and GOOGLE_CLOUD_LOCATION still need to be configured for Vertex AI."],
  },
  {
    id: "qwen-auth-menu",
    displayName: "Qwen Code: provider authentication menu",
    kind: "delegated",
    tool: "qwen-code",
    provider: "qwen",
    command: "qwen",
    args: [],
    headless: false,
    notes: ["Run /auth after Qwen Code starts. The discontinued Qwen OAuth free tier is not offered as a new login method."],
  },
  {
    id: "github-cli",
    displayName: "GitHub CLI login",
    kind: "oauth-device",
    tool: "github-copilot",
    provider: "github",
    command: "gh",
    args: ["auth", "login"],
    statusArgs: ["auth", "status"],
    logoutArgs: ["auth", "logout"],
    headless: true,
  },
];

export const authFlowMap = new Map(authFlows.map((flow) => [flow.id, flow]));

export function getAuthFlow(id: string): AuthFlow {
  const flow = authFlowMap.get(id);
  if (!flow) throw new Error(`Unknown auth flow: ${id}. Available: ${authFlows.map((item) => item.id).join(", ")}`);
  return flow;
}
